---
apiVersion: v1
kind: Secret
metadata:
  name: fencing-secret
stringData:
  fencing.yaml: |
    FencingConfig:
      computeA:
        agent: redfish
        ipaddr: 192.168.111.9
        ipport: 8000
        login: admin
        passwd: password
        uuid: UUID0
      computeB:
        agent: ipmi
        ipaddr: 192.168.111.9
        ipport: 6231
        login: admin
        passwd: password
        uuid: UUID1
