---
- name: 04 Test Instance HA
  hosts: controller-0
  gather_facts: false
  vars:
    name: "04_tag_aggregate"
  tasks:
    - name: 04 Create results file (failure)
      ansible.builtin.template:
        src: templates/iha-tests-results.xml.j2
        dest: /home/zuul/iha-tests-results/{{ name }}.xml
      vars:
        success: false

    - name: Reset iha configmap
      ansible.builtin.template:
        src: templates/iha-cm.yaml.j2
        dest: /home/zuul/iha-cm.yaml
      vars:
        tagged_aggregates: "true"
        threshold: 100

    - name: Apply config
      ansible.builtin.shell: |
        oc apply -f /home/zuul/iha-cm.yaml
      changed_when: false

    - name: 04 fetch random string
      ansible.builtin.shell:
        cmd: cat ~/.ssh/config |grep 'Host compute' |awk '{print $2}' |head -1|cut -d- -f2
      register: string
      changed_when: false

    - name: 04 set string as fact
      ansible.builtin.set_fact:
        string: "{{ string.stdout }}"

    - name: 04 Set compute-0 name as fact
      ansible.builtin.set_fact:
        compute0: "compute-{{ string }}-0.ctlplane.example.com"

    - name: 04 Set compute-1 name as fact
      ansible.builtin.set_fact:
        compute1: "compute-{{ string }}-1.ctlplane.example.com"

    - name: 04 Create ha aggregate
      openstack.cloud.host_aggregate:
        cloud: default
        auth:
          project_name: admin
        state: present
        name: iha
        availability_zone: nova
        hosts:
          - "{{ hostvars['controller-0']['compute0'] }}"

    - name: 04 Create non-ha aggregate
      openstack.cloud.host_aggregate:
        cloud: default
        auth:
          project_name: admin
        state: present
        name: nonha
        availability_zone: nova
        hosts:
          - "{{ hostvars['controller-0']['compute1'] }}"

    - name: 04 Tag aggregate
      ansible.builtin.shell: |
        openstack --os-cloud default aggregate set --property trait:CUSTOM_HA=true iha
      changed_when: false

    - name: 04 Create instance vm-ha
      openstack.cloud.server:
        cloud: default
        auth:
          project_name: admin
        state: present
        availability_zone: nova:{{ hostvars['controller-0']['compute0'] }}
        name: vm-ha
        image: cirros-0.6.2-iha-x86_64-disk.img
        timeout: 200
        flavor: m1.nano
        security_groups:
          - ping
        nics:
          - net-name: privnet

    - name: 04 Create instance vm
      openstack.cloud.server:
        cloud: default
        auth:
          project_name: admin
        state: present
        availability_zone: nova:{{ hostvars['controller-0']['compute1'] }}
        name: vm
        image: cirros-0.6.2-iha-x86_64-disk.img
        timeout: 200
        flavor: m1.nano
        security_groups:
          - ping
        nics:
          - net-name: privnet

- name: 04 Crash compute-0
  hosts: hypervisor
  remote_user: zuul
  become: true
  gather_facts: false
  tasks:
    - name: 04 Shutdown compute
      community.libvirt.virt:
        name: cifmw-compute-{{ hostvars['controller-0']['string'] }}-0
        state: destroyed

- name: 04 Check vm-ha status
  hosts: controller-0
  gather_facts: false
  tasks:
    - name: 04 Fetch HYPERVISOR for instance vm-ha
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-ha  |grep 'OS-EXT-SRV-ATTR:host ' |awk '{print $4}' |sed 's/\..*$//'
      register: hypervisor2
      changed_when: false
      retries: 60
      delay: 3
      until: hypervisor2.stdout not in hostvars['controller-0']['compute0']

    - name: 04 Fetch hypervisor for instance vm-ha
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-ha  |grep 'OS-EXT-SRV-ATTR:host ' |awk '{print $4}' |sed 's/\..*$//'
      register: hypervisor_vm_ha
      changed_when: false

    - name: 04 Check if vm was evacuated
      ansible.builtin.fail:
        msg: '"vm not evacuated"'
      when: hypervisor_vm_ha.stdout in hostvars['controller-0']['compute0']

    - name: 04 Fetch vm-ha status
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm-ha |grep vm_state |tail -1  |awk '{print $4}'
      register: vm_ha_status
      changed_when: false

    - name: 04 Check vm-ha status
      ansible.builtin.fail:
        msg: '"vm-ha should be active"'
      when: vm_ha_status.stdout != "active"

- name: 04 Crash compute-1
  hosts: hypervisor
  remote_user: zuul
  become: true
  gather_facts: false
  tasks:
    - name: 04 Shutdown compute
      community.libvirt.virt:
        name: cifmw-compute-{{ hostvars['controller-0']['string'] }}-1
        state: destroyed

- name: 04 Check vm status
  hosts: controller-0
  gather_facts: false
  tasks:
    - name: 04 Check logs
      ansible.builtin.shell: |
        oc logs deploy/instanceha-0
      register: logs
      changed_when: false
      retries: 60
      delay: 3
      until: "'not part of an evacuable aggregate' in logs.stdout"

    - name: 04 Fetch hypervisor for instance vm
      ansible.builtin.shell: |
        openstack --os-cloud default server show vm  |grep 'OS-EXT-SRV-ATTR:host ' |awk '{print $4}' |sed 's/\..*$//'
      register: hypervisor_vm
      changed_when: false

    - name: 04 Check if vm was evacuated
      ansible.builtin.fail:
        msg: '"vm evacuated, this should not happen"'
      when: hypervisor_vm.stdout not in hostvars['controller-0']['compute1']

- name: 04 Recover compute-1
  hosts: hypervisor
  remote_user: zuul
  become: true
  gather_facts: false
  tasks:
    - name: 04 Start compute-1
      community.libvirt.virt:
        name: cifmw-compute-{{ hostvars['controller-0']['string'] }}-1
        state: running

- name: 04 Cleanup
  hosts: controller-0
  gather_facts: false
  vars:
    name: "04_tag_aggregate"
  tasks:
    - name: 04 Remove vm
      openstack.cloud.server:
        cloud: default
        auth:
          project_name: admin
        state: absent
        name: vm

    - name: 04 Remove vm-ha
      openstack.cloud.server:
        cloud: default
        auth:
          project_name: admin
        state: absent
        name: vm-ha

    - name: 04 Remove aggregate
      openstack.cloud.host_aggregate:
        cloud: default
        auth:
          project_name: admin
        state: absent
        name: iha

    - name: 04 Remove aggregate
      openstack.cloud.host_aggregate:
        cloud: default
        auth:
          project_name: admin
        state: absent
        name: nonha

    - name: 04 Fetch compute service (hypervisor) info from OpenStack
      openstack.cloud.compute_service_info:
        cloud: default
        binary: nova-compute
      register: hypervisor_list

    - name: 04 Set fact
      ansible.builtin.set_fact:
        hypervisors: "{{ hypervisor_list.compute_services | map(attribute='host') | list | sort }}"

    - name: 04 Wait compute-0 to be up
      openstack.cloud.compute_service_info:
        cloud: default
        binary: nova-compute
        host: "{{ compute0 }}"
      register: compute_0_status
      until: "'up' in compute_0_status.compute_services | map(attribute='state')"
      retries: 60
      delay: 10

    - name: 04 Wait compute-1 to be up
      openstack.cloud.compute_service_info:
        cloud: default
        binary: nova-compute
        host: "{{ compute1 }}"
      register: compute_1_status
      until: "'up' in compute_1_status.compute_services | map(attribute='state')"
      retries: 60
      delay: 10

    - name: 04 save logs
      ansible.builtin.shell: oc logs deploy/instanceha-0 > /home/zuul/iha-tests-results/04_tag_aggregate.log
      changed_when: false

    - name: 04 Create results file (success)
      ansible.builtin.template:
        src: templates/iha-tests-results.xml.j2
        dest: /home/zuul/iha-tests-results/{{ name }}.xml
      vars:
        success: true
